import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    zIndex: 1000,
  },
  shadowWrapper: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 15 },
    shadowRadius: 30,
    elevation: 20,
    borderRadius: 50,
    padding: 1,
  },
  tabBar: {
    flexDirection: 'row',
    height: 74,
    borderRadius: 50,
    paddingHorizontal: 0,
    alignItems: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.2)',
  },
  edgeShading: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 65,
    zIndex: 50,
    pointerEvents: 'none',
  },
  movingIndicator: {
    position: 'absolute',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: -1,
  },
  indicatorContainer: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  activeBg: {
    width: 70,
    height: 52,
    borderRadius: 26,
    ...Platform.select({
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
      },
      android: { elevation: 0 },
    }),
    borderWidth: 0.5,
    overflow: 'hidden',
  },
  dropletHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    opacity: 0.45,
  },
  scatterGlow: {
    position: 'absolute',
    ...Platform.select({
      android: {
        width: 109,
        height: 85,
        borderRadius: 42,
        elevation: 0,
      },
      ios: {
        width: 145,
        height: 95,
        borderRadius: 47,
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.3,
        shadowRadius: 15,
      },
    }),
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  iconWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  label: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  glowBadge: {
    position: 'absolute',
    top: -2,
    right: -4,
    width: 6,
    height: 6,
    borderRadius: 3,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 5,
  },
});
